### PR TITLE
Add host parameter for redirection control

### PR DESCRIPTION
**Pull request by backspace**

### CODE REVIEW

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
I think we might need to HTML escape the `@action` (and possibly also the other values) in `become.erb`.

**Comment by backspace** [comment]
Okay, I added 48e4ded with escaping for `params[:action]`, @igorwwwwwwwwwwwwwwwwwwww. `params['login']` is escaped above so I think it’s okay?

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
@backspace The escaping needs to happen _after_ the decoding and re-encoding. In fact, I would perhaps move the escaping of `@user` and `@action` to the template.

**Comment by backspace** [comment]
hmm well I did originally have it in the template, but escaping `@user` broke everything because it’s a giant JSON object. 🤔🤔🤔

**Comment by backspace** [comment]
I added escaping for `@action` in the template and it works fine. Do you mind explaining a bit more what you mean about escaping `@user`, @igorwwwwwwwwwwwwwwwwwwww? When I try that, it fails on the client because it’s JSON, so it ends up with a bunch of `&quot;` etc.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
IIRC that was mostly about having the escaping all in one place, by moving it from the ruby code to the template. Definitely not a blocker by any means!

**Comment by backspace** [comment]
oh excellent, thank you!

**Pull request merged**
