### PR TITLE
Rewrite become as a standalone sinatra app

### PR DESCRIPTION
**Pull request by igorwwwwwwwwwwwwwwwwwwww**
No more dependencies on:

* travis-support
* travis-core
* travis-api

Thanks so much to @carlad!

### CODE REVIEW

**Comment by svenfuchs** [comment]
This looks all super, and I'd suggest to get this merged and shipped.

I think `support/database.rb` could be simplified a little, since you don't need the infrastructure for keeping multiple connections in there. But yeah, that's cool :)

Great work! Thanks!

❤️

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Changed it from travis-api to activerecord, to make it work with .com.

@svenfuchs Thanks, I simplified database as per your suggestion!

**Comment by carlad** [comment]
Shall we test this on staging now @igorwwwwwwwwwwwwwwwwwwww ?

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Yes! We need to re-deploy the travis-config for staging first.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Config has been uploaded. Deploying to staging now.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
I tested both of these and they worked for me:

* https://become-staging.travis-ci.org/carlad
* https://become-staging.travis-ci.com/carlad

**Pull request merged**
